---
- name: Add docker repo key
  when: ansible_distribution == 'Ubuntu'
  shell: "apt-key adv --keyserver {{ docker_keyserver }} --recv-keys {{ docker_repo_key }}"
  become_user: root

- name: Add docker repo
  when: ansible_distribution == 'Ubuntu'
  template: src=docker.list.j2 dest=/etc/apt/sources.list.d/docker.list owner=root mode=0644

- name: Install docker
  when: ansible_distribution == 'Ubuntu'
  apt: name=docker-engine update_cache=yes

- name: Install pip
  when: ansible_distribution == 'Ubuntu'
  apt: name=python-pip update_cache=yes

- name: Install docker-py
  pip: name=docker-py

- name: Install pyyaml
  pip: name=pyyaml

- name: Install docker-compose 
  copy: 
    src: docker-compose
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: Check for data volume
  stat: path=/dev/xvdf
  register: data_volume

- name: Create fs on data volume
  filesystem: fstype=ext4 dev=/dev/xvdf
  when: data_volume.stat.exists

- name: Mount data volume
  mount: name=/data src=/dev/xvdf fstype=ext4 state=present
  when: data_volume.stat.exists

- name: Create data subdirectories
  file: state=directory recurse=true path={{ item }} mode=777
  when: data_volume.stat.exists
  with_items:
  - /data/data/whisper
  - /data/data/elasticsearch
  - /data/data/grafana
  - /data/log/graphite
  - /data/log/elasticsearch

- name: Set docker volume options
  set_fact:
    docker_volume_options:
    - /data/data/whisper:/opt/graphite/storage/whisper
    - /data/data/elasticsearch:/var/lib/elasticsearch
    - /data/data/grafana:/opt/grafana/data
  when: data_volume.stat.exists

- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /root/

- name: create docker-compose.override.yml
  copy:
    content: |
      version: "2"
      services:
        grafana:
          ports:
            - "80:3000"
    dest: /root/docker-compose.override.yml

- name: copy sample dashboard
  copy:
    src: sampleDashboard.json
    dest: /root/sampleDashboard.json

- name: copy setup script
  copy:
    src: setup.sh
    dest: /root/setup.sh

- name: Write docker-compose.env
  template:
    src: docker-compose.env.j2
    dest: /root/docker-compose.env

# tasks file for screeps-statsd
- name: docker containers
  command: bash setup.sh
  args:
    chdir: /root